# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pepmarginallikelihoodc <- function(x, y, xnew, pred = FALSE, intrinsic = FALSE, d0 = 0, d1 = 0) {
    .Call(`_PEPBVS_pepmarginallikelihoodc`, x, y, xnew, pred, intrinsic, d0, d1)
}

full_enumeration_pepc <- function(x, gamma, y, intrinsic = FALSE, reference_prior = TRUE) {
    .Call(`_PEPBVS_full_enumeration_pepc`, x, gamma, y, intrinsic, reference_prior)
}

mc3_pepc <- function(x, y, betabinom, itermc3, current_Rsq, current_marginal, current_logpost, current_gamma, intrinsic = FALSE, reference_prior = TRUE) {
    .Call(`_PEPBVS_mc3_pepc`, x, y, betabinom, itermc3, current_Rsq, current_marginal, current_logpost, current_gamma, intrinsic, reference_prior)
}

predict_pepc <- function(x, gamma, y, xnew, intrinsic = FALSE, reference_prior = TRUE) {
    .Call(`_PEPBVS_predict_pepc`, x, gamma, y, xnew, intrinsic, reference_prior)
}

